// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZkuVA4FeRAhI36w7-ITHcpbBV9gpCClk',
    appId: '1:890441203738:web:bbeeb7a24f5a6aeb33d1a3',
    messagingSenderId: '890441203738',
    projectId: 'skilliup-db',
    authDomain: 'skilliup-db.firebaseapp.com',
    storageBucket: 'skilliup-db.firebasestorage.app',
    measurementId: 'G-XNKFX1MM5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2OmK8V4LjZ-4U4FW1bXCs0Ffpor01xm4',
    appId: '1:890441203738:android:152ab2080631dab033d1a3',
    messagingSenderId: '890441203738',
    projectId: 'skilliup-db',
    storageBucket: 'skilliup-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKOPnT0UI3DmapYxFlYGahpKpxQyKm2g8',
    appId: '1:890441203738:ios:d634ca62be69b5aa33d1a3',
    messagingSenderId: '890441203738',
    projectId: 'skilliup-db',
    storageBucket: 'skilliup-db.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKOPnT0UI3DmapYxFlYGahpKpxQyKm2g8',
    appId: '1:890441203738:ios:d634ca62be69b5aa33d1a3',
    messagingSenderId: '890441203738',
    projectId: 'skilliup-db',
    storageBucket: 'skilliup-db.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZkuVA4FeRAhI36w7-ITHcpbBV9gpCClk',
    appId: '1:890441203738:web:a42c326c91faa49b33d1a3',
    messagingSenderId: '890441203738',
    projectId: 'skilliup-db',
    authDomain: 'skilliup-db.firebaseapp.com',
    storageBucket: 'skilliup-db.firebasestorage.app',
    measurementId: 'G-58ZQRG3NT1',
  );
}
