// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS-Hlfan4Ctg7WqQjuxq_Mgtr1iPhRRdE',
    appId: '1:376050209806:web:261d69803388771d28d85f',
    messagingSenderId: '376050209806',
    projectId: 'skillup-unit',
    authDomain: 'skillup-unit.firebaseapp.com',
    storageBucket: 'skillup-unit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVh_qtPSuHyLaoCR1z2LfQ-AnM4y1lok',
    appId: '1:376050209806:android:141814c8e61b94a828d85f',
    messagingSenderId: '376050209806',
    projectId: 'skillup-unit',
    storageBucket: 'skillup-unit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Z5luK30HUZHkrtTyBetwkz8kZtjsgHA',
    appId: '1:376050209806:ios:8f6d1e6071b256f928d85f',
    messagingSenderId: '376050209806',
    projectId: 'skillup-unit',
    storageBucket: 'skillup-unit.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Z5luK30HUZHkrtTyBetwkz8kZtjsgHA',
    appId: '1:376050209806:ios:8f6d1e6071b256f928d85f',
    messagingSenderId: '376050209806',
    projectId: 'skillup-unit',
    storageBucket: 'skillup-unit.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS-Hlfan4Ctg7WqQjuxq_Mgtr1iPhRRdE',
    appId: '1:376050209806:web:76685e35c52a34b828d85f',
    messagingSenderId: '376050209806',
    projectId: 'skillup-unit',
    authDomain: 'skillup-unit.firebaseapp.com',
    storageBucket: 'skillup-unit.firebasestorage.app',
  );
}
